<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260126223802 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE alert (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(255) NOT NULL, severity VARCHAR(50) NOT NULL, message TEXT NOT NULL, value DOUBLE PRECISION NOT NULL, threshold DOUBLE PRECISION NOT NULL, is_acknowledged BOOLEAN NOT NULL, acknowledged_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, device_id INT NOT NULL, sensor_reading_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_17FD46C1A76ED395 ON alert (user_id)');
        $this->addSql('CREATE INDEX IDX_17FD46C194A4C7D4 ON alert (device_id)');
        $this->addSql('CREATE INDEX IDX_17FD46C13FD6DB8A ON alert (sensor_reading_id)');
        $this->addSql('ALTER TABLE alert ADD CONSTRAINT FK_17FD46C1A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE alert ADD CONSTRAINT FK_17FD46C194A4C7D4 FOREIGN KEY (device_id) REFERENCES device (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE alert ADD CONSTRAINT FK_17FD46C13FD6DB8A FOREIGN KEY (sensor_reading_id) REFERENCES sensor_reading (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE alert DROP CONSTRAINT FK_17FD46C1A76ED395');
        $this->addSql('ALTER TABLE alert DROP CONSTRAINT FK_17FD46C194A4C7D4');
        $this->addSql('ALTER TABLE alert DROP CONSTRAINT FK_17FD46C13FD6DB8A');
        $this->addSql('DROP TABLE alert');
    }
}
