<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260124225437 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE device (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, device_id VARCHAR(255) NOT NULL, location VARCHAR(255) DEFAULT NULL, description TEXT DEFAULT NULL, is_active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, max_temperature DOUBLE PRECISION DEFAULT NULL, min_temperature DOUBLE PRECISION DEFAULT NULL, max_co2 INT DEFAULT NULL, max_noise DOUBLE PRECISION DEFAULT NULL, user_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_92FB68EA76ED395 ON device (user_id)');
        $this->addSql('ALTER TABLE device ADD CONSTRAINT FK_92FB68EA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        
        $this->addSql('ALTER TABLE sensor_reading ADD device_identifier VARCHAR(255) DEFAULT NULL');
        
        $this->addSql('UPDATE sensor_reading SET device_identifier = device_id WHERE device_id IS NOT NULL');
        
        $this->addSql('ALTER TABLE sensor_reading ALTER COLUMN device_identifier SET NOT NULL');
        
        $this->addSql('ALTER TABLE sensor_reading ALTER COLUMN device_id DROP NOT NULL');
        
        $this->addSql('UPDATE sensor_reading SET device_id = NULL');
        
        $this->addSql('ALTER TABLE sensor_reading ALTER COLUMN device_id TYPE INT USING device_id::integer');
        
        $this->addSql('ALTER TABLE sensor_reading ADD CONSTRAINT FK_DC037B0B94A4C7D4 FOREIGN KEY (device_id) REFERENCES device (id) NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_DC037B0B94A4C7D4 ON sensor_reading (device_id)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE sensor_reading DROP CONSTRAINT FK_DC037B0B94A4C7D4');
        $this->addSql('DROP INDEX IDX_DC037B0B94A4C7D4');
        
        $this->addSql('ALTER TABLE sensor_reading ALTER device_id TYPE VARCHAR(255)');
        $this->addSql('UPDATE sensor_reading SET device_id = device_identifier');
        $this->addSql('ALTER TABLE sensor_reading ALTER device_id SET NOT NULL');
        
        $this->addSql('ALTER TABLE sensor_reading DROP device_identifier');
        
        $this->addSql('ALTER TABLE device DROP CONSTRAINT FK_92FB68EA76ED395');
        $this->addSql('DROP TABLE device');
    }
}
